# Generated by Django 4.1.5 on 2024-02-22 05:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circulation',
            name='date',
            field=models.DateField(default=datetime.time(5, 26, 48, 706248)),
        ),
    ]
