# Generated by Django 4.1.5 on 2024-02-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_books_book_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='copies',
            field=models.IntegerField(default=1),
        ),
    ]
