# Generated by Django 4.1.5 on 2024-02-22 07:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_books_copies'),
    ]

    operations = [
        migrations.AddField(
            model_name='circulation',
            name='returndate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 22, 7, 35, 39, 22767), null=True),
        ),
    ]
